apiVersion: v1
kind: Pod
metadata:
  name: pod-latest
  namespace: demo-app
  labels: { app: test-latest, owner: fedi-sayadi, environment: dev }
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext: { runAsNonRoot: true, runAsUser: 101, readOnlyRootFilesystem: true }
      resources: { requests: { cpu: "100m", memory: "64Mi" }, limits: { cpu: "250m", memory: "128Mi" } }
      livenessProbe: { httpGet: { path: /, port: 80 } }
      readinessProbe: { httpGet: { path: /, port: 80 } }
